#!/usr/bin/env tsx
/**
 * New Zealand Law MCP — Ingestion Pipeline
 *
 * Fetches New Zealand legislation XML from legislation.govt.nz /subscribe/ endpoint.
 * Data is published by the New Zealand Parliamentary Counsel Office
 * under Creative Commons Attribution 4.0 International (CC BY 4.0).
 *
 * The /subscribe/ endpoint provides structured XML files that bypass the
 * Azure WAF JavaScript challenge on the main website.
 *
 * Census-driven: reads act list from data/census.json (generated by census.ts).
 * Resume support: skips acts that already have seed files in data/seed/.
 *
 * Usage:
 *   npm run ingest                    # Full ingestion from census
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached XML files
 *   npm run ingest -- --resume        # Skip acts with existing seed files (default: on)
 *   npm run ingest -- --no-resume     # Re-ingest all acts, even if seed exists
 *
 * Data is sourced under CC BY 4.0 license.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchNzActXml } from './lib/fetcher.js';
import { parseNzXml, type ActIndexEntry, type ParsedAct } from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusEntry {
  id: string;
  year: number;
  number: string;
  subscribe_url: string;
  status: 'ingestable' | 'inaccessible';
}

interface CensusFile {
  acts: CensusEntry[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = true; // Default: resume by skipping existing seeds

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--no-resume') {
      resume = false;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Load the census file and return ingestable acts.
 */
function loadCensus(): CensusEntry[] {
  if (!fs.existsSync(CENSUS_PATH)) {
    throw new Error(`Census file not found at ${CENSUS_PATH}. Run 'npx tsx scripts/census.ts' first.`);
  }

  const data = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8')) as CensusFile;
  return data.acts.filter(a => a.status === 'ingestable');
}

/**
 * Convert a census entry to the ActIndexEntry format expected by the parser.
 * Title is discovered from the XML during ingestion and updated afterward.
 */
function censusToActEntry(census: CensusEntry): ActIndexEntry {
  const subscribeUrl = `https://www.legislation.govt.nz/act/public/${census.year}/${census.number}/latest/whole.html`;
  return {
    id: census.id,
    title: `Public Act ${census.year}/${census.number}`,
    titleEn: `Public Act ${census.year}/${census.number}`,
    shortName: `${census.year}/${census.number}`,
    status: 'in_force',
    issuedDate: `${census.year}-01-01`,
    inForceDate: `${census.year}-01-01`,
    url: subscribeUrl,
  };
}

/**
 * Extract the act title from the raw XML (cover > title element).
 * Handles attributes on cover/title elements (e.g. xml:lang="en-NZ").
 */
function extractTitleFromXml(xml: string): string | null {
  // PCO XML has <cover id="..." xml:lang="..."><title xml:lang="...">...</title></cover>
  const coverMatch = xml.match(/<cover[^>]*>([\s\S]*?)<\/cover>/i);
  if (!coverMatch) return null;

  const titleMatch = coverMatch[1].match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  if (!titleMatch) return null;

  return titleMatch[1]
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim() || null;
}

/**
 * Extract the year from root <act> element attributes (e.g. year="2020").
 */
function extractYearFromXml(xml: string): string | null {
  const match = xml.match(/<act\s[^>]*year="(\d{4})"/i);
  return match ? match[1] : null;
}

async function fetchAndParseActs(
  censusEntries: CensusEntry[],
  skipFetch: boolean,
  resume: boolean,
): Promise<void> {
  console.log(`\nProcessing ${censusEntries.length} New Zealand Acts...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let skipped = 0;
  let failed = 0;
  let networkErrors = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const MAX_CONSECUTIVE_ERRORS = 10;
  let consecutiveNetworkErrors = 0;

  const failedActs: Array<{ id: string; reason: string }> = [];

  for (const census of censusEntries) {
    const act = censusToActEntry(census);
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.xml`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip if seed already exists
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
        skipped++;
        processed++;

        // Log progress every 200 skipped acts
        if (skipped % 200 === 0) {
          console.log(`  [resumed] ${skipped} acts skipped so far...`);
        }
        continue;
      } catch {
        // Corrupted seed file, re-ingest
      }
    }

    try {
      let xml: string;

      if (fs.existsSync(sourceFile) && skipFetch) {
        xml = fs.readFileSync(sourceFile, 'utf-8');
      } else {
        // Use census year/number directly for the subscribe endpoint
        process.stdout.write(`  [${processed + 1}/${censusEntries.length}] Fetching ${act.shortName}...`);
        const result = await fetchNzActXml(
          String(census.year),
          census.number,
          'act',
          'public',
        );

        if (result.status !== 200) {
          console.log(` HTTP ${result.status}`);
          failedActs.push({ id: act.id, reason: `http-${result.status}` });
          failed++;
          processed++;
          consecutiveNetworkErrors = 0;
          continue;
        }

        // Verify we got XML (not an HTML error page or WAF challenge)
        if (!result.body.includes('<?xml') && !result.body.includes('<act ') && !result.body.includes('<act>')) {
          console.log(` ERROR: Response is not XML (got ${result.contentType})`);
          failedActs.push({ id: act.id, reason: 'not-xml' });
          failed++;
          processed++;
          continue;
        }

        xml = result.body;
        fs.writeFileSync(sourceFile, xml);
        consecutiveNetworkErrors = 0;

        const sizeKB = (xml.length / 1024).toFixed(0);
        process.stdout.write(` OK (${sizeKB} KB)`);
      }

      // Discover title from XML and update the act entry
      const discoveredTitle = extractTitleFromXml(xml);
      if (discoveredTitle) {
        act.title = discoveredTitle;
        act.titleEn = discoveredTitle;
        act.shortName = discoveredTitle;
      }

      // Discover issued year from XML
      const discoveredYear = extractYearFromXml(xml);
      if (discoveredYear) {
        act.issuedDate = `${discoveredYear}-01-01`;
      }

      const parsed = parseNzXml(xml, act);
      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));
      totalProvisions += parsed.provisions.length;
      totalDefinitions += parsed.definitions.length;
      console.log(` -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      const isNetworkError = msg.includes('fetch failed') || msg.includes('TIMEOUT') || msg.includes('ECONNRESET');

      if (isNetworkError) {
        networkErrors++;
        consecutiveNetworkErrors++;
        console.log(` NETWORK ERROR: ${msg}`);

        if (consecutiveNetworkErrors >= MAX_CONSECUTIVE_ERRORS) {
          console.log(`\n  FATAL: ${MAX_CONSECUTIVE_ERRORS} consecutive network errors.`);
          console.log(`  Saving progress. Re-run to resume from where we left off.`);
          break;
        }

        // Wait longer after network errors
        await new Promise(resolve => setTimeout(resolve, 5000));
      } else {
        console.log(` PARSE ERROR: ${msg}`);
        consecutiveNetworkErrors = 0;
      }

      failedActs.push({ id: act.id, reason: msg.substring(0, 100) });
      failed++;
    }

    processed++;

    // Log progress every 50 acts
    if (processed % 50 === 0) {
      console.log(`\n  --- Progress: ${processed}/${censusEntries.length} (${totalProvisions} provisions, ${failed} failed) ---\n`);
    }
  }

  // Print summary report
  console.log('\n========================================');
  console.log('Ingestion Report');
  console.log('========================================\n');

  console.log(`  Processed:        ${processed}`);
  console.log(`  Skipped (cached): ${skipped}`);
  console.log(`  Failed:           ${failed}`);
  console.log(`  Network errors:   ${networkErrors}`);
  console.log(`  Total provisions: ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  if (failedActs.length > 0 && failedActs.length <= 50) {
    console.log('\n  Failed acts:');
    for (const f of failedActs) {
      console.log(`    ${f.id}: ${f.reason}`);
    }
  } else if (failedActs.length > 50) {
    console.log(`\n  ${failedActs.length} acts failed. First 20:`);
    for (const f of failedActs.slice(0, 20)) {
      console.log(`    ${f.id}: ${f.reason}`);
    }
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('New Zealand Law MCP — Ingestion Pipeline');
  console.log('========================================\n');
  console.log(`  Source: legislation.govt.nz /subscribe/ (XML)`);
  console.log(`  License: CC BY 4.0`);
  console.log(`  Census: ${CENSUS_PATH}`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skipping existing seeds)`);

  const allActs = loadCensus();
  console.log(`  Census: ${allActs.length} ingestable acts`);

  const acts = limit ? allActs.slice(0, limit) : allActs;
  await fetchAndParseActs(acts, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
